export {default as DashboardHead} from './DashboardHead'
export {default as DashboardMainGraph} from './DashboardMainGraph'
export {default as DashboardOrderTable} from './DashboardOrderTable'
export {default as DashboardSecondaryGraph} from './DashboardSecondaryGraph'
export {default as MainInfoSummary} from './MainInfoSummary'
export {default as MainSummaryCard} from './MainSummaryCard'
export {default as MitraTopSalesCard} from './MitraTopSalesCard'
export {default as QuickAccess} from './QuickAccess'